[[constraint]]
  name = "github.com/erizocosmico/gocloc"
  branch = "master"

[[constraint]]
  name = "gopkg.in/src-d/go-license-detector.v1"
  version = "1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  revision = "1bb87923d7c8dd4df78e96d46a254a3dcf24a360"
  name = "gopkg.in/src-d/core-retrieval.v0"

[[constraint]]
  name = "gopkg.in/src-d/enry.v1"
  version = "1.6.3"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.1.0"

[[override]]
  revision = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e"
  name = "github.com/satori/go.uuid"

[prune]
  go-tests = true
  unused-packages = true
